name: Release Zip Chrome Extension
on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Zip Chrome Extension
        run: zip -r BreezeAds_chrome_${{ github.event.release.tag_name }}.zip src/chrome

      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: BreezeAds_chrome_${{ github.event.release.tag_name }}.zip